name: redeploy

on:
  push:
    branches:
      - main

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: send redeploy request
        uses: wei/curl@master
        with:
          args: ${{ secrets.redeploy_url }}
